version: '3.8'

services:
  gamafut:
    container_name: gamafut_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # Mapeia a porta 80 do container (Nginx) para a porta 3150 do seu host (Zima OS).
      - "3150:80"
    # Define o nome da rede para facilitar a gest√£o no Zima OS (opcional, mas recomendado)
    networks:
      - default
    restart: always

networks:
  default:
    driver: bridge