version: '3.8'

services:
  gamafut:
    container_name: gamafut_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # Mapeia a porta 80 do container (Nginx) para a porta 8080 do seu host.
      - "8080:80"
    restart: always