version: '3.8'

services:
  gamafut:
    container_name: gamafut_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # Mapeia a porta 80 do container (Nginx) para a porta 3150 do seu host.
      - "3150:80"
    restart: always